### ISSUE TITLE
[taier-ui编译异常][taier-ui] taier-ui编译异常

### ISSUE THREAD

**Issue by niutaofan** [DTStack/Taier#1125] opened 2023-10-31 11:35 UTC
### Search before asking

- [x] I had searched in the [issues](https://github.com/DTStack/Taier/issues) and found no similar question.

- [X] I had searched my question on the internet but i didn't get any help.

- [X] I had read the documentation: [Taier doc](https://dtstack.github.io/Taier) but it didn't help me.

### Description

使用命令：在taier-ui目录下执行：npm run build
报错：
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'run', 'build' ]
2 info using npm@6.14.6
3 info using node@v12.18.3
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle @~prebuild: @
6 info lifecycle @~build: @
7 verbose lifecycle @~build: unsafe-perm in lifecycle true
8 verbose lifecycle @~build: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Applications/tools/mygithub/Taier/taier-ui/node_modules/.bin:/Users/yiche1/miniconda3/bin:/Applications/tools/gitlab/apache-hive-3.1.2-src/bin:/Users/yiche1/Documents/protobuf-2.5.0/bin:/Applications/tools/javacc/bin:/usr/local/go/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/usr/local/mysql-connector-c-6.1.10-macos10.12-x86_64/bin/:/usr/local/mysql/bin:/usr/local/mysql/bin:/Applications/tools/apache-maven-3.6.3/bin:/bin:/Applications/tools/gitlab/hadoop-3.1.1/bin:/Applications/tools/gitlab/hadoop-3.1.1/sbin:/Applications/tools/gradle-6.7/bin:/Applications/tools/scala-2.12.8/bin
9 verbose lifecycle @~build: CWD: /Applications/tools/mygithub/Taier/taier-ui
10 silly lifecycle @~build: Args: [ '-c', 'umi build' ]
11 silly lifecycle @~build: Returned: code: 1  signal: null
12 info lifecycle @~build: Failed to exec build script
13 verbose stack Error: @ build: `umi build`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:315:20)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:315:20)
13 verbose stack     at maybeClose (internal/child_process.js:1021:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
14 verbose pkgid @
15 verbose cwd /Applications/tools/mygithub/Taier/taier-ui
16 verbose Darwin 22.1.0
17 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "build"
18 verbose node v12.18.3
19 verbose npm  v6.14.6
20 error code ELIFECYCLE
21 error errno 1
22 error @ build: `umi build`
22 error Exit status 1
23 error Failed at the @ build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by niutaofan** [comment] 2023-11-01 11:08
[INFO] Scanning for projects...
[INFO] 
[INFO] ---------------------< com.dtstack.taier:taier-ui >---------------------
[INFO] Building taier-ui 1.0.0
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ taier-ui ---
[INFO] Deleting /Applications/tools/mygithub/Taier/taier-ui/target
[INFO] 
[INFO] --- jacoco-maven-plugin:0.7.8:prepare-agent (default) @ taier-ui ---
[INFO] argLine set to -javaagent:/Applications/tools/repository/org/jacoco/org.jacoco.agent/0.7.8/org.jacoco.agent-0.7.8-runtime.jar=destfile=/Applications/tools/mygithub/Taier/taier-ui/target/jacoco.exec
[INFO] 
[INFO] --- frontend-maven-plugin:1.12.1:install-node-and-yarn (install node and yarn) @ taier-ui ---
[INFO] Installing node version v16.16.0
[INFO] Unpacking /Applications/tools/repository/com/github/eirslett/node/16.16.0/node-16.16.0-darwin-x64.tar.gz into /Applications/tools/mygithub/Taier/taier-ui/target/node/tmp
[INFO] Copying node binary from /Applications/tools/mygithub/Taier/taier-ui/target/node/tmp/node-v16.16.0-darwin-x64/bin/node to /Applications/tools/mygithub/Taier/taier-ui/target/node/node
[INFO] Installed node locally.
[INFO] Installing Yarn version v1.22.19
[INFO] Unpacking /Applications/tools/repository/com/github/eirslett/yarn/1.22.19/yarn-1.22.19.tar.gz into /Applications/tools/mygithub/Taier/taier-ui/target/node/yarn
[INFO] Installed Yarn locally.
[INFO] 
[INFO] --- frontend-maven-plugin:1.12.1:yarn (yarn config) @ taier-ui ---
[INFO] Running 'yarn config set registry https://registry.npm.taobao.org' in /Applications/tools/mygithub/Taier/taier-ui/target
[INFO] yarn config v1.22.19
[INFO] success Set "registry" to "https://registry.npm.taobao.org".
[INFO] Done in 0.07s.
[INFO] 
[INFO] --- frontend-maven-plugin:1.12.1:yarn (yarn install) @ taier-ui ---
[INFO] Running 'yarn ' in /Applications/tools/mygithub/Taier/taier-ui/target
[INFO] yarn install v1.22.19
[INFO] warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
[INFO] [1/5] Validating package.json...
[INFO] [2/5] Resolving packages...
[INFO] success Already up-to-date.
[INFO] $ umi generate tmp
[INFO] Done in 4.40s.
[INFO] 
[INFO] --- frontend-maven-plugin:1.12.1:yarn (yarn run build) @ taier-ui ---
[INFO] Running 'yarn run build' in /Applications/tools/mygithub/Taier/taier-ui/target
[INFO] yarn run v1.22.19
[INFO] $ umi build
[INFO] Bundle with webpack 5...
[INFO] ℹ Compiling Webpack
[INFO] (node:92995) [DEP_WEBPACK_CONFIGURATION_OPTIMIZATION_NO_EMIT_ON_ERRORS] DeprecationWarning: optimization.noEmitOnErrors is deprecated in favor of optimization.emitOnErrors
[INFO] (Use `node --trace-deprecation ...` to show where the warning was created)
[INFO] (node:92995) [DEP_WEBPACK_COMPILATION_OPTIMIZE_CHUNK_ASSETS] DeprecationWarning: optimizeChunkAssets is deprecated (use Compilation.hooks.processAssets instead and use one of Compilation.PROCESS_ASSETS_STAGE_* as stage option)
[INFO] Browserslist: caniuse-lite is outdated. Please run:
[INFO] npx browserslist@latest --update-db
[INFO] 
[INFO] Why you should do it regularly:
[INFO] https://github.com/browserslist/browserslist#browsers-data-updating
[INFO] ✔ Webpack: Compiled with some errors in 1.66m
[INFO]  ERROR  Failed to compile with 1 errors7:07:22 PM
[INFO] 
[INFO]  error  in ./node_modules/antlr4-c3/lib/index.mjs
[INFO] 
[INFO] Module parse failed: Unexpected token (1697:9)
[INFO] You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
[INFO] |   static COMPLETE_CHAR_SET = i13.of(N.MIN_CHAR_VALUE, N.MAX_CHAR_VALUE);
[INFO] |   static EMPTY_SET = new i13();
[INFO] >   static {
[INFO] |     i13.COMPLETE_CHAR_SET.readonly = true, i13.EMPTY_SET.readonly = true;
[INFO] |   }
[INFO] 
[INFO] ERROR in ./node_modules/antlr4-c3/lib/index.mjs 1697:9
[INFO] ERROR in ./node_modules/antlr4-c3/lib/index.mjs 1697:9null
[INFO] Module parse failed: Unexpected token (1697:9)
[INFO] You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
[INFO] |   static COMPLETE_CHAR_SET = i13.of(N.MIN_CHAR_VALUE, N.MAX_CHAR_VALUE);
[INFO] |   static EMPTY_SET = new i13();
[INFO] >   static {
[INFO] |     i13.COMPLETE_CHAR_SET.readonly = true, i13.EMPTY_SET.readonly = true;
[INFO] |   }
[INFO]  @ ./node_modules/dt-sql-parser/dist/parser/common/basicParser.js 3:0-47 221:25-43
[INFO]  @ ./node_modules/dt-sql-parser/dist/parser/generic.js 3:0-47 4:40-51
[INFO]  @ ./node_modules/monaco-sql-languages/out/esm/sql/sqlWorker.js 1:0-54 7:26-31
[INFO]  @ ./node_modules/monaco-sql-languages/out/esm/sql/sql.worker.js 2:0-40 5:19-28
[INFO]  @ ./node_modules/monaco-sql-languages/out/esm/sql/sql.worker.js 2:0-40 5:19-28build failed
[INFO] 
[INFO] webpack compiled with 1 error
[INFO]  info  如果你需要进交流群，请访问 https://fb.umijs.org
[INFO] Error: build failed
[INFO] Error: build failed info  如果你需要进交流群，请访问 https://fb.umijs.org
[INFO]     at /Applications/tools/mygithub/Taier/taier-ui/node_modules/@umijs/bundler-webpack/lib/index.js:177:29
[INFO]     at /Applications/tools/mygithub/Taier/taier-ui/node_modules/@umijs/deps/compiled/webpack/5/bundle5.js:114591:14
[INFO]     at processQueueWorker (/Applications/tools/mygithub/Taier/taier-ui/node_modules/@umijs/deps/compiled/webpack/5/bundle5.js:114529:6)
[INFO]     at processTicksAndRejections (node:internal/process/task_queues:78:11)
[INFO] error Command failed with exit code 1.
[INFO] error Command failed with exit code 1.info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  01:53 min
[INFO] Finished at: 2023-11-01T19:07:22+08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.12.1:yarn (yarn run build) on project taier-ui: Failed to run task: 'yarn run build' failed. org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1) -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

**Comment by mortalYoung** [comment] 2023-11-01 11:15
Duplicate of #1122

**Closed** 2023-11-01 11:16 UTC
Labels: question
